sudo: false
distr : "trusty"

language: generic

before_install:

  # Install python
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

 # pytest
  - conda install -c anaconda pytest
  - conda install -c conda-forge pytest-cov
  - conda install python=3.6

  # install freesasa python bindings
  # - pip install freesasa==2.0.3.post4 # <- doesn't work anymore

  # install freesasa
  # - conda install cython
  # - git clone https://github.com/freesasa/freesasa-python
  # - cd freesasa-python
  # - git submodule update --init
  # - USE_CYTHON=1 python setup.py build
  # - export PYTHONPATH=$PYTHONPATH: ???

  # install freesasa
  - conda install cython
  - sudo apt-get install -y libxml2 libxml2-dev libjson0 libjson0-dev
  - wget http://github.com/mittinatten/freesasa/releases/download/2.0.2/freesasa-2.0.2.tar.gz
  - mkdir freesasa
  - tar -xvf freesasa-2.0.2.tar.gz -C freesasa --strip-components=1
  - cd freesasa
  - ./configure --disable-xml --disable-json --enable-python-bindings --with-python=python3.6 CFLAGS="-fPIC" --prefix=$HOME
  - make
  - make install
  - cd ../


  # install pytorch
  - conda install pytorch=0.4.0 torchvision cuda80 -c soumith

  # codacy-coverage
  - pip install -q --upgrade pip
  - pip install -q coverage
  - pip install -q codacy-coverage
  - pip install -q coveralls


install:
  - pip install -qe .[test]

script:
  - cd test/
  - pytest --cov=deeprank --cov-report xml:coverage.xml
  - mv coverage.xml ../
  - mv .coverage ../
  - cd ../

after_script:
- python-codacy-coverage -r coverage.xml
- coveralls
